name: Automated Code Review with Copilot (Opus 4.5)

on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'crates/**'
      - 'Cargo.toml'
      - 'Cargo.lock'
      - '.github/workflows/code-review.yml'
  workflow_dispatch:

jobs:
  review:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # - name: Collect repository structure and specification
      #   id: repo_context
      #   run: |
      #     mkdir -p /tmp
          
      #     {
      #       echo "## Repository Structure"
      #       find crates -type f -name "Cargo.toml" | sort
      #       echo ""
      #       echo "## Specification"
      #       cat .agent/rules/system-prompt.md
      #       echo ""
      #       echo "## Key Source Files"
      #       for file in crates/*/src/lib.rs; do
      #         if [ -f "$file" ]; then
      #           echo "### $file"
      #           head -50 "$file"
      #           echo "..."
      #         fi
      #       done
      #     } > /tmp/repo_context.txt
          
      #     echo "context_file=/tmp/repo_context.txt" >> $GITHUB_OUTPUT

      - name: Create Pull Request with Review
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "docs(review): Claude-generated code review for ${{ steps.claude_review.outputs.review_date }}"
          title: "📋 Automated Code Review - ${{ steps.claude_review.outputs.review_date }}"
          body: |
            # 📋 Code Review - Generated by Claude Opus
            
            ## Review Prompt
            
            Review the code comprehensively, including comparison with the spec in system-prompt.md.
            
            Write a full report of each package and file with compliance or violation found of:
            1. The spec
            2. Security concerns
            3. Coding concerns and best practices
            
            Use ✅/❌/⚠️ emoji style for status indicators.
            
            Format the report as Markdown with clear sections for each package, spec violations, 
            security concerns, and best practices recommendations.
            
            Include:
            - Spec Compliance tables (Requirement | Status | Notes)
            - Security Concerns tables
            - Coding Best Practices tables
            - Summary sections for critical violations, moderate issues, and successes
            - Actionable recommendations
            - Use of secrets (RED FLAG if any secrets are hardcoded)

            Also, review the .github/workflows for compliance with:
            - Security best practices
            - Use of secrets (RED FLAG if any secrets are hardcoded)
            
            ---
            
            ## Review Output
            
            See attached review file: `docs/reviews/${{ steps.claude_review.outputs.review_date }}.md`
            
            This PR contains the complete analysis generated by Claude Opus based on the specification and project structure.
          branch: "reviews/claude-${{ steps.claude_review.outputs.review_date }}"
          delete-branch: true
          labels: "review,automated,documentation"

      # Can restore if artifact upload is desired

      # - name: Upload review artifact
      #   uses: actions/upload-artifact@v3
      #   if: always()
      #   with:
      #     name: code-review-${{ steps.claude_review.outputs.review_date }}
      #     path: docs/reviews/${{ steps.claude_review.outputs.review_date }}.md
      #     retention-days: 90
